[versions]
accompanist-permissions = "0.24.9-beta"
android-gradle-plugin = "7.3.1"
androidx-activity = "1.6.1"
androidx-lifecycle = "2.4.1"
androidx-wear-compose = "1.1.0"
compose = "1.3.1"
compose-compiler = "1.3.2"
concurrent-futures = "1.1.0"
guava = "30.1.1-android"
health-services = "1.0.0-beta01"
ktlint = "0.46.1"
org-jetbrains-kotlin = "1.7.20"
org-jetbrains-kotlinx = "1.6.0"

[libraries]
accompanist-permissions = { module = "com.google.accompanist:accompanist-permissions", version.ref = "accompanist-permissions" }
android-lint-gradle = "com.android.tools.lint:lint-gradle:30.3.1"
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidx-activity" }
androidx-health-services = { module = "androidx.health:health-services-client", version.ref = "health-services" }
androidx-lifecycle-viewmodel-compose = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "androidx-lifecycle" }
compose-compiler = { module = "androidx.compose.compiler:compiler", version.ref = "compose-compiler" }
compose-material-icons-extended = { module = "androidx.compose.material:material-icons-extended", version.ref = "compose" }
compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "compose" }
compose-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview", version.ref = "compose" }
concurrent-futures = { module = "androidx.concurrent:concurrent-futures-ktx", version.ref = "concurrent-futures" }
guava = { module = "com.google.guava:guava", version.ref = "guava" }
kotlin-gradle-plugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "org-jetbrains-kotlin" }
wear-compose-foundation = { module = "androidx.wear.compose:compose-foundation", version.ref = "androidx-wear-compose" }
wear-compose-material = { module = "androidx.wear.compose:compose-material", version.ref = "androidx-wear-compose" }

[plugins]
com-android-application = { id = "com.android.application", version.ref = "android-gradle-plugin" }
com-diffplug-spotless = "com.diffplug.spotless:6.12.0"
org-jetbrains-kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "org-jetbrains-kotlin" }
