[versions]
android-gradle-plugin = "8.1.2"
androidx-activity = "1.8.0"
androidx-compose = "1.5.4"
androidx-lifecycle = "2.6.2"
androidx-wear-compose = "1.2.1"
core-splashscreen = "1.0.1"
dagger = "2.48.1"
health-services = "1.0.0-rc01"
horologist = "0.5.9"
org-jetbrains-kotlin = "1.9.10"

[libraries]
android-lint-gradle = "com.android.tools.lint:lint-gradle:31.1.2"
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidx-activity" }
androidx-compose-navigation = "androidx.navigation:navigation-compose:2.7.4"
androidx-compose-runtime = "androidx.compose.runtime:runtime:1.5.4"
androidx-compose-ui-tooling = { module = "androidx.wear.compose:compose-ui-tooling", version.ref = "androidx-wear-compose" }
androidx-concurrent = "androidx.concurrent:concurrent-futures-ktx:1.1.0"
androidx-core-splashscreen = { module = "androidx.core:core-splashscreen", version.ref = "core-splashscreen" }
androidx-health-services = { module = "androidx.health:health-services-client", version.ref = "health-services" }
androidx-lifecycle-common-java8 = { module = "androidx.lifecycle:lifecycle-common-java8", version.ref = "androidx-lifecycle"}
androidx-lifecycle-extensions  = "androidx.lifecycle:lifecycle-extensions:2.2.0"
androidx-lifecycle-runtime = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "androidx-lifecycle"}
androidx-lifecycle-runtime-compose = "androidx.lifecycle:lifecycle-runtime-compose:2.6.2"
androidx-lifecycle-service = {module = "androidx.lifecycle:lifecycle-service", version.ref = "androidx-lifecycle"}
androidx-lifecycle-viewmodel = {module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "androidx-lifecycle"}
androidx-material-icons-extended = { module = "androidx.compose.material:material-icons-extended", version.ref = "androidx-compose" }
androidx-wear = "androidx.wear:wear:1.3.0"
compose-compiler = "androidx.compose.compiler:compiler:1.5.3"
compose-ui-test-junit4 = { module = "androidx.compose.ui:ui-test-junit4", version.ref = "androidx-compose" }
compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "androidx-compose" }
compose-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview", version.ref = "androidx-compose" }
compose-wear-navigation = "androidx.wear.compose:compose-navigation:1.2.1"
dagger-hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "dagger"}
dagger-hilt-android-compiler = {module = "com.google.dagger:hilt-android-compiler", version.ref = "dagger"}
guava = "com.google.guava:guava:32.1.3-android"
hilt-navigation-compose = "androidx.hilt:hilt-navigation-compose:1.0.0"
horologist-compose-layout = { module = "com.google.android.horologist:horologist-compose-layout", version.ref = "horologist" }
horologist-compose-material = { module = "com.google.android.horologist:horologist-compose-material", version.ref = "horologist" }
horologist-health-composables = { module = "com.google.android.horologist:horologist-health-composables", version.ref = "horologist" }
horologist-health-service = { module = "com.google.android.horologist:horologist-health-service", version.ref = "horologist" }
jacoco-ant = "org.jacoco:org.jacoco.ant:0.8.11"
junit = "junit:junit:4.13.2"
test-espresso-core = "androidx.test.espresso:espresso-core:3.5.1"
test-ext-junit = "androidx.test.ext:junit:1.1.5"
wear-compose-foundation = { module = "androidx.wear.compose:compose-foundation", version.ref = "androidx-wear-compose" }
wear-compose-material = { module = "androidx.wear.compose:compose-material", version.ref = "androidx-wear-compose" }
wear-ongoing-activity = "androidx.wear:wear-ongoing:1.0.0"


[plugins]
com-android-application = { id = "com.android.application", version.ref = "android-gradle-plugin" }
dagger-hilt = { id = "com.google.dagger.hilt.android", version.ref = "dagger"}
org-jetbrains-kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "org-jetbrains-kotlin" }


